server:
  port: 8080

spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    cache-names: redisCache
    type: redis
  redis:
    port: 6379
    password: lims
    host: localhost
  # spring security\u76F8\u5173\u914D\u7F6E\u3001 \u5B9E\u9645\u60C5\u51B5,\u4E0D\u53EF\u80FD\u53EA\u6709\u4E00\u4E2A\u7528\u6237\u3001\u90FD\u662F\u6570\u636E\u5E93\u4E2D\u53D6\u51FA\u7528\u6237\u548C\u89D2\u8272\u3001
  security:
    user:
      name: luxf
      password: 123456
      roles: ROLE_ADMIN
# Spring Aop configuration.
  aop:
    auto: true
    proxy-target-class: true # false：使用JDK动态代理、 true：使用CGLIB动态代理, 默认true！ 使用@import导入AopAutoConfiguration.class即可、

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.luxf.mybatis.bootmybatisdemo.entity
  configuration:
    default-executor-type: SIMPLE
    cache-enabled: false
    aggressive-lazy-loading: true
    use-column-label: true
    lazy-loading-enabled: false
    use-generated-keys: false
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
    safe-row-bounds-enabled: false
    safe-result-handler-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    return-instance-for-empty-row: false
    use-actual-param-name: true
    local-cache-scope: statement

#showSql
logging:
  level:
    com:
      luxf: DEBUG
    #   Spring Boot的相关日志
    org:
      springframework:
        boot: DEBUG

# 自定义的@ConfigurationProperties对象、
custom:
  mybatis:
    refresh:
      enabled: true
      delay-seconds: 5
      interval-seconds: 3
      mapper-suffix: Mapper.xml